export const browserCoreExamples = [
  "keanu browser status",
  "keanu browser start",
  "keanu browser stop",
  "keanu browser tabs",
  "keanu browser open https://example.com",
  "keanu browser focus abcd1234",
  "keanu browser close abcd1234",
  "keanu browser screenshot",
  "keanu browser screenshot --full-page",
  "keanu browser screenshot --ref 12",
  "keanu browser snapshot",
  "keanu browser snapshot --format aria --limit 200",
  "keanu browser snapshot --efficient",
  "keanu browser snapshot --labels",
];

export const browserActionExamples = [
  "keanu browser navigate https://example.com",
  "keanu browser resize 1280 720",
  "keanu browser click 12 --double",
  'keanu browser type 23 "hello" --submit',
  "keanu browser press Enter",
  "keanu browser hover 44",
  "keanu browser drag 10 11",
  "keanu browser select 9 OptionA OptionB",
  "keanu browser upload /tmp/keanu/uploads/file.pdf",
  'keanu browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "keanu browser dialog --accept",
  'keanu browser wait --text "Done"',
  "keanu browser evaluate --fn '(el) => el.textContent' --ref 7",
  "keanu browser console --level error",
  "keanu browser pdf",
];
