#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${KEANU_INSTALL_E2E_IMAGE:-${KEANU_INSTALL_E2E_IMAGE:-openclaw-install-e2e:local}}"
INSTALL_URL="${KEANU_INSTALL_URL:-${KEANU_INSTALL_URL:-https://openclaw.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
KEANU_E2E_MODELS="${KEANU_E2E_MODELS:-${KEANU_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e KEANU_INSTALL_URL="$INSTALL_URL" \
  -e KEANU_INSTALL_TAG="${KEANU_INSTALL_TAG:-${KEANU_INSTALL_TAG:-latest}}" \
  -e KEANU_E2E_MODELS="$KEANU_E2E_MODELS" \
  -e KEANU_INSTALL_E2E_PREVIOUS="${KEANU_INSTALL_E2E_PREVIOUS:-${KEANU_INSTALL_E2E_PREVIOUS:-}}" \
  -e KEANU_INSTALL_E2E_SKIP_PREVIOUS="${KEANU_INSTALL_E2E_SKIP_PREVIOUS:-${KEANU_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
